// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class CargosPaciente
{
    public int CargoPacienteId { get; set; }

    public int PacienteId { get; set; }

    public int? ProductoId { get; set; }

    public int? ServicioId { get; set; }

    public int UsuarioCreacionId { get; set; }

    public string TipoCargo { get; set; }

    public decimal Cantidad { get; set; }

    public decimal PrecioUnitario { get; set; }

    public DateTime FechaHoraCargo { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Paciente Paciente { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Servicio Servicio { get; set; }

    public virtual Usuario UsuarioCreacion { get; set; }
}