// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Cita
{
    public int CitaId { get; set; }

    public int PacienteId { get; set; }

    public int TipoCitaId { get; set; }

    public int EstadoCitaId { get; set; }

    public int? VeterinarioId { get; set; }

    public int UsuarioCreacionId { get; set; }

    public DateTime FechaHoraInicioProgramada { get; set; }

    public DateTime FechaHoraFinProgramada { get; set; }

    public string Observaciones { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public virtual EstadosCita EstadoCita { get; set; }

    public virtual Paciente Paciente { get; set; }

    public virtual TiposCita TipoCita { get; set; }

    public virtual Usuario UsuarioCreacion { get; set; }

    public virtual Empleado Veterinario { get; set; }

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();
}