// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Cliente
{
    public int ClienteId { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Cedula { get; set; }

    public string TelefonoPrincipal { get; set; }

    public string TelefonoEmergencia { get; set; }

    public string Direccion { get; set; }

    public string CorreoElectronico { get; set; }

    public string MetodoPagoPreferido { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<Paciente> Pacientes { get; set; } = new List<Paciente>();
}