// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Empleado
{
    public int EmpleadoId { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Cedula { get; set; }

    public string Telefono { get; set; }

    public string CorreoElectronico { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool? EstaActivo { get; set; }

    public virtual ICollection<Cita> Cita { get; set; } = new List<Cita>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();

    public virtual ICollection<VacunacionesPaciente> VacunacionesPacientes { get; set; } = new List<VacunacionesPaciente>();

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();
}