// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Especy
{
    public int EspecieId { get; set; }

    public string NombreEspecie { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<Paciente> Pacientes { get; set; } = new List<Paciente>();

    public virtual ICollection<Raza> Razas { get; set; } = new List<Raza>();
}