// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class EstadosGuarderia
{
    public int EstadoGuarderiaId { get; set; }

    public string NombreEstado { get; set; }

    public virtual ICollection<EstanciasGuarderium> EstanciasGuarderia { get; set; } = new List<EstanciasGuarderium>();
}