// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class EstanciasGuarderium
{
    public int EstanciaGuarderiaId { get; set; }

    public int PacienteId { get; set; }

    public int EstadoGuarderiaId { get; set; }

    public int UsuarioCreacionId { get; set; }

    public DateTime FechaHoraEntrada { get; set; }

    public DateTime? FechaHoraSalida { get; set; }

    public string InstruccionesAlimentacion { get; set; }

    public string InstruccionesSocializacion { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual EstadosGuarderia EstadoGuarderia { get; set; }

    public virtual Paciente Paciente { get; set; }

    public virtual ICollection<PertenenciasGuarderium> PertenenciasGuarderia { get; set; } = new List<PertenenciasGuarderium>();

    public virtual Usuario UsuarioCreacion { get; set; }
}