// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Paciente
{
    public int PacienteId { get; set; }

    public int ClienteId { get; set; }

    public int EspecieId { get; set; }

    public int? RazaId { get; set; }

    public string NombrePaciente { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public string Sexo { get; set; }

    public string ColorPelaje { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<CargosPaciente> CargosPacientes { get; set; } = new List<CargosPaciente>();

    public virtual ICollection<Cita> Cita { get; set; } = new List<Cita>();

    public virtual Cliente Cliente { get; set; }

    public virtual Especy Especie { get; set; }

    public virtual ICollection<EstanciasGuarderium> EstanciasGuarderia { get; set; } = new List<EstanciasGuarderium>();

    public virtual Raza Raza { get; set; }

    public virtual ICollection<VacunacionesPaciente> VacunacionesPacientes { get; set; } = new List<VacunacionesPaciente>();

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();
}