// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Permiso
{
    public int PermisoId { get; set; }

    public string CodigoPermiso { get; set; }

    public string NombrePermiso { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<PermisosRole> PermisosRoles { get; set; } = new List<PermisosRole>();
}