// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class PermisosRole
{
    public int? RolId { get; set; }

    public int PermisosRolesId { get; set; }

    public int? PermisoId { get; set; }

    public DateTime FechaAsignacion { get; set; }

    public virtual Permiso Permiso { get; set; }

    public virtual Role Rol { get; set; }
}