// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class PertenenciasGuarderium
{
    public int PertenenciaGuarderiaId { get; set; }

    public int EstanciaGuarderiaId { get; set; }

    public string DescripcionPertenencia { get; set; }

    public virtual EstanciasGuarderium EstanciaGuarderia { get; set; }
}