// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Producto
{
    public int ProductoId { get; set; }

    public string CodigoProducto { get; set; }

    public string NombreProducto { get; set; }

    public string TipoProducto { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<CargosPaciente> CargosPacientes { get; set; } = new List<CargosPaciente>();
}