// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class RegistrosAuditorium
{
    public int RegistroAuditoriaId { get; set; }

    public int? UsuarioId { get; set; }

    public string NombreEntidad { get; set; }

    public string IdentificadorEntidad { get; set; }

    public string TipoAccion { get; set; }

    public DateTime FechaHoraEvento { get; set; }

    public string ValoresAnteriores { get; set; }

    public string ValoresNuevos { get; set; }

    public virtual Usuario Usuario { get; set; }
}