// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class RolesUsuario
{
    public int? UsuarioId { get; set; }

    public int RolesUsuarioId { get; set; }

    public int? RolId { get; set; }

    public DateTime FechaAsignacion { get; set; }

    public virtual Role Rol { get; set; }

    public virtual Usuario Usuario { get; set; }
}