// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Servicio
{
    public int ServicioId { get; set; }

    public string CodigoServicio { get; set; }

    public string NombreServicio { get; set; }

    public string CategoriaServicio { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<CargosPaciente> CargosPacientes { get; set; } = new List<CargosPaciente>();
}