// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class TiposCita
{
    public int TipoCitaId { get; set; }

    public string NombreTipoCita { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<Cita> Cita { get; set; } = new List<Cita>();
}