// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class TiposVisita
{
    public int TipoVisitaId { get; set; }

    public string NombreTipoVisita { get; set; }

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();
}