// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Usuario
{
    public int UsuarioId { get; set; }

    public int EmpleadoId { get; set; }

    public string NombreUsuario { get; set; }

    public string HashContrasena { get; set; }

    public DateTime? FechaUltimaSesion { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaActualizacion { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<CargosPaciente> CargosPacientes { get; set; } = new List<CargosPaciente>();

    public virtual ICollection<Cita> Cita { get; set; } = new List<Cita>();

    public virtual Empleado Empleado { get; set; }

    public virtual ICollection<EstanciasGuarderium> EstanciasGuarderia { get; set; } = new List<EstanciasGuarderium>();

    public virtual ICollection<RegistrosAuditorium> RegistrosAuditoria { get; set; } = new List<RegistrosAuditorium>();

    public virtual ICollection<RolesUsuario> RolesUsuarios { get; set; } = new List<RolesUsuario>();

    public virtual ICollection<VacunacionesPaciente> VacunacionesPacientes { get; set; } = new List<VacunacionesPaciente>();

    public virtual ICollection<Visita> Visita { get; set; } = new List<Visita>();
}