// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Vacuna
{
    public int VacunaId { get; set; }

    public string NombreVacuna { get; set; }

    public string Fabricante { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<VacunacionesPaciente> VacunacionesPacientes { get; set; } = new List<VacunacionesPaciente>();
}