// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class VacunacionesPaciente
{
    public int VacunacionPacienteId { get; set; }

    public int PacienteId { get; set; }

    public int VacunaId { get; set; }

    public int? AsistenteId { get; set; }

    public int UsuarioCreacionId { get; set; }

    public DateTime FechaHoraAplicacion { get; set; }

    public DateOnly? FechaProximaAplicacion { get; set; }

    public string Observaciones { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Empleado Asistente { get; set; }

    public virtual Paciente Paciente { get; set; }

    public virtual Usuario UsuarioCreacion { get; set; }

    public virtual Vacuna Vacuna { get; set; }
}