// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace app_vetcare_si.Models.Entities;

public partial class Visita
{
    public int VisitaId { get; set; }

    public int PacienteId { get; set; }

    public int TipoVisitaId { get; set; }

    public int? VeterinarioId { get; set; }

    public int? CitaId { get; set; }

    public int UsuarioCreacionId { get; set; }

    public DateTime FechaHoraVisita { get; set; }

    public string Motivo { get; set; }

    public decimal? PesoKg { get; set; }

    public decimal? TemperaturaC { get; set; }

    public string Observaciones { get; set; }

    public DateTime FechaCreacion { get; set; }

    public virtual Cita Cita { get; set; }

    public virtual Paciente Paciente { get; set; }

    public virtual TiposVisita TipoVisita { get; set; }

    public virtual Usuario UsuarioCreacion { get; set; }

    public virtual Empleado Veterinario { get; set; }
}