// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using app_vetcare_si.Models.Entities;

namespace app_vetcare_si.Data;

public partial class DevVetCareDBSIContext : DbContext
{
    public DevVetCareDBSIContext()
    {
    }

    public DevVetCareDBSIContext(DbContextOptions<DevVetCareDBSIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CargosPaciente> CargosPacientes { get; set; }

    public virtual DbSet<Cita> Citas { get; set; }

    public virtual DbSet<Cliente> Clientes { get; set; }

    public virtual DbSet<Empleado> Empleados { get; set; }

    public virtual DbSet<Especy> Especies { get; set; }

    public virtual DbSet<EstadosCita> EstadosCitas { get; set; }

    public virtual DbSet<EstadosGuarderia> EstadosGuarderias { get; set; }

    public virtual DbSet<EstanciasGuarderium> EstanciasGuarderia { get; set; }

    public virtual DbSet<Paciente> Pacientes { get; set; }

    public virtual DbSet<Permiso> Permisos { get; set; }

    public virtual DbSet<PermisosRole> PermisosRoles { get; set; }

    public virtual DbSet<PertenenciasGuarderium> PertenenciasGuarderia { get; set; }

    public virtual DbSet<Producto> Productos { get; set; }

    public virtual DbSet<Raza> Razas { get; set; }

    public virtual DbSet<RegistrosAuditorium> RegistrosAuditoria { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolesUsuario> RolesUsuarios { get; set; }

    public virtual DbSet<Servicio> Servicios { get; set; }

    public virtual DbSet<TiposCita> TiposCitas { get; set; }

    public virtual DbSet<TiposVisita> TiposVisitas { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    public virtual DbSet<Vacuna> Vacunas { get; set; }

    public virtual DbSet<VacunacionesPaciente> VacunacionesPacientes { get; set; }

    public virtual DbSet<Visita> Visitas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=LNNB-NOTEBOOK\\DB_SQLSERVER;Initial Catalog=dev_vetcare_si2v;Integrated Security=True;Encrypt=True;Trust Server Certificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CargosPaciente>(entity =>
        {
            entity.HasKey(e => e.CargoPacienteId).IsClustered(false);

            entity.Property(e => e.CargoPacienteId).ValueGeneratedNever();
            entity.Property(e => e.Cantidad)
                .HasDefaultValue(1m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CargosPacientes_Cantidad")
                .HasColumnType("decimal(12, 3)");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CargosPacientes_FechaCreacion");
            entity.Property(e => e.FechaHoraCargo)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CargosPacientes_FechaHoraCargo");
            entity.Property(e => e.PrecioUnitario).HasColumnType("decimal(19, 4)");
            entity.Property(e => e.TipoCargo)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Paciente).WithMany(p => p.CargosPacientes)
                .HasForeignKey(d => d.PacienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CargosPacientes_Pacientes");

            entity.HasOne(d => d.Producto).WithMany(p => p.CargosPacientes)
                .HasForeignKey(d => d.ProductoId)
                .HasConstraintName("FK_CargosPacientes_Productos");

            entity.HasOne(d => d.Servicio).WithMany(p => p.CargosPacientes)
                .HasForeignKey(d => d.ServicioId)
                .HasConstraintName("FK_CargosPacientes_Servicios");

            entity.HasOne(d => d.UsuarioCreacion).WithMany(p => p.CargosPacientes)
                .HasForeignKey(d => d.UsuarioCreacionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CargosPacientes_Usuarios");
        });

        modelBuilder.Entity<Cita>(entity =>
        {
            entity.HasKey(e => e.CitaId).IsClustered(false);

            entity.Property(e => e.CitaId).ValueGeneratedNever();
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Citas_FechaCreacion");
            entity.Property(e => e.Observaciones).HasMaxLength(1000);

            entity.HasOne(d => d.EstadoCita).WithMany(p => p.Cita)
                .HasForeignKey(d => d.EstadoCitaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Citas_EstadosCitas");

            entity.HasOne(d => d.Paciente).WithMany(p => p.Cita)
                .HasForeignKey(d => d.PacienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Citas_Pacientes");

            entity.HasOne(d => d.TipoCita).WithMany(p => p.Cita)
                .HasForeignKey(d => d.TipoCitaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Citas_TiposCitas");

            entity.HasOne(d => d.UsuarioCreacion).WithMany(p => p.Cita)
                .HasForeignKey(d => d.UsuarioCreacionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Citas_Usuarios");

            entity.HasOne(d => d.Veterinario).WithMany(p => p.Cita)
                .HasForeignKey(d => d.VeterinarioId)
                .HasConstraintName("FK_Citas_Veterinarios");
        });

        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.ClienteId).IsClustered(false);

            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Cedula).HasMaxLength(50);
            entity.Property(e => e.CorreoElectronico).HasMaxLength(254);
            entity.Property(e => e.Direccion).HasMaxLength(300);
            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Clientes_EstaActivo");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Clientes_FechaCreacion");
            entity.Property(e => e.MetodoPagoPreferido).HasMaxLength(50);
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TelefonoEmergencia).HasMaxLength(30);
            entity.Property(e => e.TelefonoPrincipal)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<Empleado>(entity =>
        {
            entity.HasKey(e => e.EmpleadoId).IsClustered(false);

            entity.Property(e => e.Apellido)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Cedula).HasMaxLength(50);
            entity.Property(e => e.CorreoElectronico).HasMaxLength(254);
            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Empleados_EstaActivo");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Empleados_FechaCreacion");
            entity.Property(e => e.Nombre)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Telefono).HasMaxLength(30);
        });

        modelBuilder.Entity<Especy>(entity =>
        {
            entity.HasKey(e => e.EspecieId).IsClustered(false);

            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Especies_EstaActivo");
            entity.Property(e => e.NombreEspecie)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<EstadosCita>(entity =>
        {
            entity.HasKey(e => e.EstadoCitaId).IsClustered(false);

            entity.Property(e => e.NombreEstado)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<EstadosGuarderia>(entity =>
        {
            entity.HasKey(e => e.EstadoGuarderiaId).IsClustered(false);

            entity.Property(e => e.NombreEstado)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<EstanciasGuarderium>(entity =>
        {
            entity.HasKey(e => e.EstanciaGuarderiaId).IsClustered(false);

            entity.Property(e => e.EstanciaGuarderiaId).ValueGeneratedNever();
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EstanciasGuarderia_FechaCreacion");
            entity.Property(e => e.InstruccionesAlimentacion).HasMaxLength(1000);
            entity.Property(e => e.InstruccionesSocializacion).HasMaxLength(1000);

            entity.HasOne(d => d.EstadoGuarderia).WithMany(p => p.EstanciasGuarderia)
                .HasForeignKey(d => d.EstadoGuarderiaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EstanciasGuarderia_Estados");

            entity.HasOne(d => d.Paciente).WithMany(p => p.EstanciasGuarderia)
                .HasForeignKey(d => d.PacienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EstanciasGuarderia_Pacientes");

            entity.HasOne(d => d.UsuarioCreacion).WithMany(p => p.EstanciasGuarderia)
                .HasForeignKey(d => d.UsuarioCreacionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EstanciasGuarderia_Usuarios");
        });

        modelBuilder.Entity<Paciente>(entity =>
        {
            entity.HasKey(e => e.PacienteId).IsClustered(false);

            entity.Property(e => e.ColorPelaje).HasMaxLength(100);
            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Pacientes_EstaActivo");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Pacientes_FechaCreacion");
            entity.Property(e => e.NombrePaciente)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Sexo)
                .HasMaxLength(24)
                .IsUnicode(false)
                .IsFixedLength();

            entity.HasOne(d => d.Cliente).WithMany(p => p.Pacientes)
                .HasForeignKey(d => d.ClienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pacientes_Clientes");

            entity.HasOne(d => d.Especie).WithMany(p => p.Pacientes)
                .HasForeignKey(d => d.EspecieId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pacientes_Especies");

            entity.HasOne(d => d.Raza).WithMany(p => p.Pacientes)
                .HasForeignKey(d => d.RazaId)
                .HasConstraintName("FK_Pacientes_Razas");
        });

        modelBuilder.Entity<Permiso>(entity =>
        {
            entity.HasKey(e => e.PermisoId).IsClustered(false);

            entity.Property(e => e.CodigoPermiso)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Permisos_EstaActivo");
            entity.Property(e => e.NombrePermiso)
                .IsRequired()
                .HasMaxLength(150);
        });

        modelBuilder.Entity<PermisosRole>(entity =>
        {
            entity.HasKey(e => e.PermisosRolesId).IsClustered(false);

            entity.Property(e => e.FechaAsignacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PermisosRoles_FechaAsignacion");

            entity.HasOne(d => d.Permiso).WithMany(p => p.PermisosRoles)
                .HasForeignKey(d => d.PermisoId)
                .HasConstraintName("FK_PermisosRoles_Permisos");

            entity.HasOne(d => d.Rol).WithMany(p => p.PermisosRoles)
                .HasForeignKey(d => d.RolId)
                .HasConstraintName("FK_PermisosRoles_Roles");
        });

        modelBuilder.Entity<PertenenciasGuarderium>(entity =>
        {
            entity.HasKey(e => e.PertenenciaGuarderiaId).IsClustered(false);

            entity.Property(e => e.PertenenciaGuarderiaId).ValueGeneratedNever();
            entity.Property(e => e.DescripcionPertenencia)
                .IsRequired()
                .HasMaxLength(300);

            entity.HasOne(d => d.EstanciaGuarderia).WithMany(p => p.PertenenciasGuarderia)
                .HasForeignKey(d => d.EstanciaGuarderiaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PertenenciasGuarderia_Estancias");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.ProductoId).IsClustered(false);

            entity.Property(e => e.CodigoProducto)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Productos_EstaActivo");
            entity.Property(e => e.NombreProducto)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.TipoProducto)
                .IsRequired()
                .HasMaxLength(30);
        });

        modelBuilder.Entity<Raza>(entity =>
        {
            entity.HasKey(e => e.RazaId).IsClustered(false);

            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Razas_EstaActivo");
            entity.Property(e => e.NombreRaza)
                .IsRequired()
                .HasMaxLength(150);

            entity.HasOne(d => d.Especie).WithMany(p => p.Razas)
                .HasForeignKey(d => d.EspecieId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Razas_Especies");
        });

        modelBuilder.Entity<RegistrosAuditorium>(entity =>
        {
            entity.HasKey(e => e.RegistroAuditoriaId).IsClustered(false);

            entity.Property(e => e.RegistroAuditoriaId).ValueGeneratedNever();
            entity.Property(e => e.FechaHoraEvento)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RegistrosAuditoria_FechaHoraEvento");
            entity.Property(e => e.IdentificadorEntidad)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.NombreEntidad)
                .IsRequired()
                .HasMaxLength(128);
            entity.Property(e => e.TipoAccion)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Usuario).WithMany(p => p.RegistrosAuditoria)
                .HasForeignKey(d => d.UsuarioId)
                .HasConstraintName("FK_RegistrosAuditoria_Usuarios");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RolId).IsClustered(false);

            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_EstaActivo");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Roles_FechaCreacion");
            entity.Property(e => e.NombreRol)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<RolesUsuario>(entity =>
        {
            entity.HasKey(e => e.RolesUsuarioId).IsClustered(false);

            entity.Property(e => e.FechaAsignacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RolesUsuarios_FechaAsignacion");

            entity.HasOne(d => d.Rol).WithMany(p => p.RolesUsuarios)
                .HasForeignKey(d => d.RolId)
                .HasConstraintName("FK_RolesUsuarios_Roles");

            entity.HasOne(d => d.Usuario).WithMany(p => p.RolesUsuarios)
                .HasForeignKey(d => d.UsuarioId)
                .HasConstraintName("FK_RolesUsuarios_Usuarios");
        });

        modelBuilder.Entity<Servicio>(entity =>
        {
            entity.HasKey(e => e.ServicioId).IsClustered(false);

            entity.Property(e => e.CategoriaServicio)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CodigoServicio)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Servicios_EstaActivo");
            entity.Property(e => e.NombreServicio)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<TiposCita>(entity =>
        {
            entity.HasKey(e => e.TipoCitaId).IsClustered(false);

            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TiposCitas_EstaActivo");
            entity.Property(e => e.NombreTipoCita)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<TiposVisita>(entity =>
        {
            entity.HasKey(e => e.TipoVisitaId).IsClustered(false);

            entity.Property(e => e.NombreTipoVisita)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.UsuarioId).IsClustered(false);

            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Usuarios_EstaActivo");
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Usuarios_FechaCreacion");
            entity.Property(e => e.HashContrasena)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.NombreUsuario)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Empleado).WithMany(p => p.Usuarios)
                .HasForeignKey(d => d.EmpleadoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuarios_Empleados");
        });

        modelBuilder.Entity<Vacuna>(entity =>
        {
            entity.HasKey(e => e.VacunaId).IsClustered(false);

            entity.Property(e => e.EstaActivo)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Vacunas_EstaActivo");
            entity.Property(e => e.Fabricante).HasMaxLength(200);
            entity.Property(e => e.NombreVacuna)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<VacunacionesPaciente>(entity =>
        {
            entity.HasKey(e => e.VacunacionPacienteId).IsClustered(false);

            entity.Property(e => e.VacunacionPacienteId).ValueGeneratedNever();
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_VacunacionesPacientes_FechaCreacion");
            entity.Property(e => e.Observaciones).HasMaxLength(500);

            entity.HasOne(d => d.Asistente).WithMany(p => p.VacunacionesPacientes)
                .HasForeignKey(d => d.AsistenteId)
                .HasConstraintName("FK_VacunacionesPacientes_Empleados");

            entity.HasOne(d => d.Paciente).WithMany(p => p.VacunacionesPacientes)
                .HasForeignKey(d => d.PacienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VacunacionesPacientes_Pacientes");

            entity.HasOne(d => d.UsuarioCreacion).WithMany(p => p.VacunacionesPacientes)
                .HasForeignKey(d => d.UsuarioCreacionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VacunacionesPacientes_Usuarios");

            entity.HasOne(d => d.Vacuna).WithMany(p => p.VacunacionesPacientes)
                .HasForeignKey(d => d.VacunaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_VacunacionesPacientes_Vacunas");
        });

        modelBuilder.Entity<Visita>(entity =>
        {
            entity.HasKey(e => e.VisitaId).IsClustered(false);

            entity.Property(e => e.VisitaId).ValueGeneratedNever();
            entity.Property(e => e.FechaCreacion)
                .HasDefaultValueSql("(sysdatetime())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Visitas_FechaCreacion");
            entity.Property(e => e.Motivo).HasMaxLength(500);
            entity.Property(e => e.Observaciones).HasMaxLength(2000);
            entity.Property(e => e.PesoKg).HasColumnType("decimal(8, 3)");
            entity.Property(e => e.TemperaturaC).HasColumnType("decimal(5, 2)");

            entity.HasOne(d => d.Cita).WithMany(p => p.Visita)
                .HasForeignKey(d => d.CitaId)
                .HasConstraintName("FK_Visitas_Citas");

            entity.HasOne(d => d.Paciente).WithMany(p => p.Visita)
                .HasForeignKey(d => d.PacienteId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Visitas_Pacientes");

            entity.HasOne(d => d.TipoVisita).WithMany(p => p.Visita)
                .HasForeignKey(d => d.TipoVisitaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Visitas_TiposVisitas");

            entity.HasOne(d => d.UsuarioCreacion).WithMany(p => p.Visita)
                .HasForeignKey(d => d.UsuarioCreacionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Visitas_Usuarios");

            entity.HasOne(d => d.Veterinario).WithMany(p => p.Visita)
                .HasForeignKey(d => d.VeterinarioId)
                .HasConstraintName("FK_Visitas_Veterinarios");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}